#  Veriyi Yükleme ve İlk Bakış

In [1]:
import pandas as pd
import numpy as np

df_ham = pd.read_csv('Superstore.csv', encoding='latin1')

print("Boyut:", df_ham.shape)

df_ham.head()

Boyut: (9994, 21)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-BO-10001798,Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,2,CA-2016-152156,11/8/2016,11/11/2016,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,42420,South,FUR-CH-10000454,Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,3,CA-2016-138688,6/12/2016,6/16/2016,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,90036,West,OFF-LA-10000240,Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,4,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,FUR-TA-10000577,Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,5,US-2015-108966,10/11/2015,10/18/2015,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,33311,South,OFF-ST-10000760,Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [2]:
df_ham.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Row ID         9994 non-null   int64
 1   Order ID       9994 non-null   object
 2   Order Date     9994 non-null   object
 3   Ship Date      9994 non-null   object
 4   Ship Mode      9994 non-null   object
 5   Customer ID    9994 non-null   object
 6   Customer Name  9994 non-null   object
 7   Segment        9994 non-null   object
 8   Country        9994 non-null   object
 9   City           9994 non-null   object
 10  State          9994 non-null   object
 11  Postal Code    9994 non-null   int64
 12  Region         9994 non-null   object
 13  Product ID     9994 non-null   object
 14  Category       9994 non-null   object
 15  Sub-Category   9994 non-null   object
 16  Product Name   9994 non-null   object
 17  Sales          9994 non-null   float64
 18  Quantity       9994 non-null   int64
 19  Discount       9994 non-null   float64
 20  Profit         9994 non-null   float64
dtypes: float64(3), int64(3), object(15)
memory usage: 1.6+ MB

In [3]:
print("Sütun bazında eksik değer sayısı:")
print(df_ham.isnull().sum())

print("\nToplam tekrar eden satır sayısı:", df_ham.duplicated().sum())

Sütun bazında eksik değer sayısı:
Row ID           0
Order ID         0
Order Date       0
Ship Date        0
Ship Mode        0
Customer ID      0
Customer Name    0
Segment          0
Country          0
City             0
State            0
Postal Code      0
Region           0
Product ID       0
Category         0
Sub-Category     0
Product Name     0
Sales            0
Quantity         0
Discount         0
Profit           0
dtype: int64

Toplam tekrar eden satır sayısı: 0

In [4]:
df_ham['Order Date'] = pd.to_datetime(df_ham['Order Date'])
df_ham['Ship Date'] = pd.to_datetime(df_ham['Ship Date'])

In [5]:
df_ham[['Order Date', 'Ship Date']].dtypes

Order Date    datetime64[ns]
Ship Date     datetime64[ns]
dtype: object

In [6]:
df_ham['Order Date'].dt.year

0       2016
1       2016
2       2016
3       2015
4       2015
        ...
9989    2014
9990    2017
9991    2017
9992    2017
9993    2017
Name: Order Date, Length: 9994, dtype: int32

In [7]:
df_ham['Order Date'].dt.month

0       11
1       11
2        6
3       10
4       10
        ..
9989     1
9990     2
9991     2
9992     2
9993     5
Name: Order Date, Length: 9994, dtype: int32

In [8]:
df_ham['Ship Date'] - df_ham['Order Date'] # teslimat süresi

0      3 days
1      3 days
2      4 days
3      7 days
4      7 days
        ...
9989   2 days
9990   5 days
9991   5 days
9992   5 days
9993   5 days
Length: 9994, dtype: timedelta64[ns]

In [9]:
df_ham['Order Year'] = df_ham['Order Date'].dt.year
df_ham['Order Month'] = df_ham['Order Date'].dt.month
df_ham['Shipping Duration'] = df_ham['Ship Date'] - df_ham['Order Date']

In [10]:
df_ham[['Order Date', 'Ship Date', 'Order Year', 'Order Month', 'Shipping Duration']].head()

  Order Date  Ship Date  Order Year  Order Month Shipping Duration
0 2016-11-08 2016-11-11        2016           11            3 days
1 2016-11-08 2016-11-11        2016           11            3 days
2 2016-06-12 2016-06-16        2016            6            4 days
3 2015-10-11 2015-10-18        2015           10            7 days
4 2015-10-11 2015-10-18        2015           10            7 days

In [11]:
df_ham[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales     Quantity     Discount       Profit
count   9994.000000  9994.000000  9994.000000  9994.000000
mean     229.858001     3.789574     0.156203    28.656896
std      623.245101     2.225110     0.206452   234.260108
min        0.444000     1.000000     0.000000 -6599.978000
25%       17.280000     2.000000     0.000000     1.728750
50%       54.490000     3.000000     0.200000     8.666500
75%      209.940000     5.000000     0.200000    29.364000
max    22638.480000    14.000000     0.800000  8399.976000

In [12]:
print("Negatif Sales sayısı:", (df_ham['Sales'] < 0).sum())
print("Sıfır veya negatif Quantity sayısı:", (df_ham['Quantity'] <= 0).sum())
print("Discount 0'dan küçük:", (df_ham['Discount'] < 0).sum())
print("Discount 1'den büyük:", (df_ham['Discount'] > 1).sum())

Negatif Sales sayısı: 0
Sıfır veya negatif Quantity sayısı: 0
Discount 0'dan küçük: 0
Discount 1'den büyük: 0

In [13]:
Q1 = df_ham[['Sales', 'Profit']].quantile(0.25)
Q3 = df_ham[['Sales', 'Profit']].quantile(0.75)

IQR = Q3 - Q1

alt_sinir = Q1 - 1.5 * IQR
ust_sinir = Q3 + 1.5 * IQR

print("Alt sınırlar:")
print(alt_sinir)

print("\nÜst sınırlar:")
print(ust_sinir)

Alt sınırlar:
Sales    -271.710000
Profit    -39.724125
dtype: float64

Üst sınırlar:
Sales     498.930000
Profit     70.816875
dtype: float64

In [14]:
aykiri_sales = df_ham[
    (df_ham['Sales'] < alt_sinir['Sales']) |
    (df_ham['Sales'] > ust_sinir['Sales'])
]

aykiri_profit = df_ham[
    (df_ham['Profit'] < alt_sinir['Profit']) |
    (df_ham['Profit'] > ust_sinir['Profit'])
]

print("Sales aykırı değer sayısı:", len(aykiri_sales))
print("Profit aykırı değer sayısı:", len(aykiri_profit))

Sales aykırı değer sayısı: 1167
Profit aykırı değer sayısı: 1881

In [15]:
aykiri_sales[['Order ID', 'Product Name', 'Category', 'Sales', 'Quantity', 'Discount', 'Profit']].sort_values(
    'Sales', ascending=False
).head(10)

,Order ID,Product Name,Category,Sales,Quantity,Discount,Profit
2697,CA-2014-145317,Cisco TelePresence System EX90 Videoconferenci...,Technology,22638.480,6,0.5,-1811.0784
6826,CA-2016-118689,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,5,0.0,8399.9760
8153,CA-2017-140151,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,4,0.0,6719.9808
2623,CA-2017-127180,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,4,0.2,3919.9888
4190,CA-2017-166709,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,3,0.0,5039.9856
9039,CA-2016-117121,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,13,0.0,4946.3700
4098,CA-2014-116904,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,5,0.0,4630.4755
4277,US-2016-107440,"3D Systems Cube Printer, 2nd Generation, Magenta",Technology,9099.930,7,0.0,2365.9818
8488,CA-2016-158841,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,5,0.0,2799.9840
6425,CA-2016-143714,Canon imageCLASS 2200 Advanced Copier,Technology,8399.976,4,0.4,1119.9968

In [16]:
aykiri_profit[['Order ID', 'Product Name', 'Category', 'Sales', 'Quantity', 'Discount', 'Profit']].sort_values(
    'Profit', ascending=False
).head(10)

,Order ID,Product Name,Category,Sales,Quantity,Discount,Profit
6826,CA-2016-118689,Canon imageCLASS 2200 Advanced Copier,Technology,17499.950,5,0.0,8399.9760
8153,CA-2017-140151,Canon imageCLASS 2200 Advanced Copier,Technology,13999.960,4,0.0,6719.9808
4190,CA-2017-166709,Canon imageCLASS 2200 Advanced Copier,Technology,10499.970,3,0.0,5039.9856
9039,CA-2016-117121,GBC Ibimaster 500 Manual ProClick Binding System,Office Supplies,9892.740,13,0.0,4946.3700
4098,CA-2014-116904,Ibico EPK-21 Electric Binding System,Office Supplies,9449.950,5,0.0,4630.4755
2623,CA-2017-127180,Canon imageCLASS 2200 Advanced Copier,Technology,11199.968,4,0.2,3919.9888
509,CA-2015-145352,Fellowes PB500 Electric Punch Plastic Comb Bin...,Office Supplies,6354.950,5,0.0,3177.4750
8488,CA-2016-158841,HP Designjet T520 Inkjet Large Format Printer ...,Technology,8749.950,5,0.0,2799.9840
7666,US-2016-140158,Hewlett Packard LaserJet 3310 Copier,Technology,5399.910,9,0.0,2591.9568
6520,CA-2017-138289,GBC DocuBind P400 Electric Binding System,Office Supplies,5443.960,4,0.0,2504.2216

## Kritere Göre Tekrar Eden Kayıt Kontrolü

In [17]:
tekrar_sayisi = df_ham.duplicated(subset=['Customer ID', 'Order Date', 'Product ID']).sum()
print(f"Müşteri + sipariş tarihi + ürün bazında tekrar eden kayıt sayısı: {tekrar_sayisi}")

Müşteri + sipariş tarihi + ürün bazında tekrar eden kayıt sayısı: 8

##  Kategori Tutarlılığı Kontrolü

In [18]:
kategorik_sutunlar = ['Category', 'Sub-Category', 'Region', 'Segment', 'Ship Mode']

for sutun in kategorik_sutunlar:
    print(f"{sutun}: {sorted(df_ham[sutun].unique())}")
    print()

Category: ['Furniture', 'Office Supplies', 'Technology']

Sub-Category: ['Accessories', 'Appliances', 'Art', 'Binders', 'Bookcases', 'Chairs', 'Copiers', 'Envelopes', 'Fasteners', 'Furnishings', 'Labels', 'Machines', 'Paper', 'Phones', 'Storage', 'Supplies', 'Tables']

Region: ['Central', 'East', 'South', 'West']

Segment: ['Consumer', 'Corporate', 'Home Office']

Ship Mode: ['First Class', 'Same Day', 'Second Class', 'Standard Class']

In [19]:
# Baştaki/sondaki boşluk kontrolü (tüm metin sütunları için)
metin_sutunlari = df_ham.select_dtypes(include='object').columns
bosluk_bulundu = False

for sutun in metin_sutunlari:
    bosluk_sorunu = (df_ham[sutun] != df_ham[sutun].str.strip()).sum()
    if bosluk_sorunu > 0:
        bosluk_bulundu = True
        print(f"{sutun}: {bosluk_sorunu} satırda baştaki/sondaki boşluk sorunu var")

if not bosluk_bulundu:
    print("Boşluk sorunu bulunmadı.")

Product Name: 16 satırda baştaki/sondaki boşluk sorunu var

In [20]:
# Product Name sütunundaki boşluk sorununu düzeltelim
df_ham['Product Name'] = df_ham['Product Name'].str.strip()

kalan_sorun = (df_ham['Product Name'] != df_ham['Product Name'].str.strip()).sum()
print(f"Düzeltme sonrası 'Product Name' sütununda kalan boşluk sorunu: {kalan_sorun}")

Düzeltme sonrası 'Product Name' sütununda kalan boşluk sorunu: 0

##  Aykırı Değerlerin Ele Alınması,

In [21]:
df_ham['Sales_Aykiri'] = (df_ham['Sales'] < alt_sinir['Sales']) | (df_ham['Sales'] > ust_sinir['Sales'])
df_ham['Profit_Aykiri'] = (df_ham['Profit'] < alt_sinir['Profit']) | (df_ham['Profit'] > ust_sinir['Profit'])

print("Sales aykırı olarak işaretlenen satır sayısı:", df_ham['Sales_Aykiri'].sum())
print("Profit aykırı olarak işaretlenen satır sayısı:", df_ham['Profit_Aykiri'].sum())

Sales aykırı olarak işaretlenen satır sayısı: 1167
Profit aykırı olarak işaretlenen satır sayısı: 1881

##  İndeks Düzenleme

In [22]:
df_ham = df_ham.reset_index(drop=True)
print("İndeks sıfırlandı. İndeks aralığı:", df_ham.index.min(), "-", df_ham.index.max())

İndeks sıfırlandı. İndeks aralığı: 0 - 9993

##  Temizlenmiş Veriyi Kaydetme

In [23]:
df_ham.to_csv('Superstore_temiz.csv', index=False)
print("Temizlenmiş veri 'Superstore_temiz.csv' olarak kaydedildi.")
print("\nSon durumun genel bilgisi:")
df_ham.info()

Temizlenmiş veri 'Superstore_temiz.csv' olarak kaydedildi.

Son durumun genel bilgisi:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Row ID             9994 non-null   int64
 1   Order ID           9994 non-null   object
 2   Order Date         9994 non-null   datetime64[ns]
 3   Ship Date          9994 non-null   datetime64[ns]
 4   Ship Mode          9994 non-null   object
 5   Customer ID        9994 non-null   object
 6   Customer Name      9994 non-null   object
 7   Segment            9994 non-null   object
 8   Country            9994 non-null   object
 9   City               9994 non-null   object
 10  State              9994 non-null   object
 11  Postal Code        9994 non-null   int64
 12  Region             9994 non-null   object
 13  Product ID         9994 non-null   object
 14  Category           9994 non-null   object
 15  Sub-Category       9994 non-null   object
 16  Product Name       9994 non-null   object
 17  Sales              9994 non-null   float64
 18  Quantity           9994 non-null   int64
 19  Discount           9994 non-null   float64
 20  Profit             9994 non-null   float64
 21  Order Year         9994 non-null   int32
 22  Order Month        9994 non-null   int32
 23  Shipping Duration  9994 non-null   timedelta64[ns]
 24  Sales_Aykiri       9994 non-null   bool
 25  Profit_Aykiri      9994 non-null   bool
dtypes: bool(2), datetime64[ns](2), float64(3), int32(2), int64(3), object(13), timedelta64[ns](1)
memory usage: 1.8+ MB

##  Uçtan Uca Temizleme Fonksiyonu

In [24]:
def veriyi_temizle(df_ham_girdi):

    df = df_ham_girdi.copy()


    df['Order Date'] = pd.to_datetime(df['Order Date'])
    df['Ship Date'] = pd.to_datetime(df['Ship Date'])


    df['Order Year'] = df['Order Date'].dt.year
    df['Order Month'] = df['Order Date'].dt.month
    df['Shipping Duration'] = df['Ship Date'] - df['Order Date']

    df['Product Name'] = df['Product Name'].str.strip()

    Q1 = df[['Sales', 'Profit']].quantile(0.25)
    Q3 = df[['Sales', 'Profit']].quantile(0.75)
    IQR = Q3 - Q1
    alt = Q1 - 1.5 * IQR
    ust = Q3 + 1.5 * IQR
    df['Sales_Aykiri'] = (df['Sales'] < alt['Sales']) | (df['Sales'] > ust['Sales'])
    df['Profit_Aykiri'] = (df['Profit'] < alt['Profit']) | (df['Profit'] > ust['Profit'])

    df = df.reset_index(drop=True)

    return df

df_test = veriyi_temizle(pd.read_csv('Superstore.csv', encoding='latin1'))
print("Fonksiyon testi - boyut:", df_test.shape)
df_test.head()

Fonksiyon testi - boyut: (9994, 26)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Shipping Duration,Sales_Aykiri,Profit_Aykiri
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,3 days,False,False
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,3 days,True,True
2,3,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,United States,Los Angeles,...,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,2016,6,4 days,False,False
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,7 days,True,True
4,5,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,2015,10,7 days,False,False

##  Veri Seçme ve Filtreleme

In [25]:
# Belirli sütunları inceleme
df_ham[['Customer Name', 'Category', 'Sales', 'Profit']].head()

     Customer Name         Category     Sales    Profit
0      Claire Gute        Furniture  261.9600   41.9136
1      Claire Gute        Furniture  731.9400  219.5820
2  Darrin Van Huff  Office Supplies   14.6200    6.8714
3   Sean O'Donnell        Furniture  957.5775 -383.0310
4   Sean O'Donnell  Office Supplies   22.3680    2.5164

In [26]:
# .loc ile ilk satırın belirli sütunlarını seçme
df_ham.loc[0, ['Customer Name', 'Category', 'Sales', 'Profit']]

Customer Name    Claire Gute
Category           Furniture
Sales                 261.96
Profit               41.9136
Name: 0, dtype: object

In [27]:
# Koşullu filtreleme: 'Furniture' kategorisindeki siparişler
df_ham[df_ham['Category'] == 'Furniture'].head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country,City,...,Product Name,Sales,Quantity,Discount,Profit,Order Year,Order Month,Shipping Duration,Sales_Aykiri,Profit_Aykiri
0,1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,2016,11,3 days,False,False
1,2,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,United States,Henderson,...,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2016,11,3 days,True,True
3,4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,United States,Fort Lauderdale,...,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,2015,10,7 days,True,True
5,6,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Eldon Expressions Wood and Plastic Desk Access...,48.8600,7,0.00,14.1694,2014,6,5 days,False,False
10,11,CA-2014-115812,2014-06-09,2014-06-14,Standard Class,BH-11710,Brosina Hoffman,Consumer,United States,Los Angeles,...,Chromcraft Rectangular Conference Tables,1706.1840,9,0.20,85.3092,2014,6,5 days,True,True

In [28]:
# Birden fazla koşul: Profit negatif VE kategori 'Furniture' olanlar (zarar eden mobilya satışları)
df_ham[(df_ham['Profit'] < 0) & (df_ham['Category'] == 'Furniture')][
    ['Product Name', 'Sales', 'Discount', 'Profit']
].head()

,Product Name,Sales,Discount,Profit
3,Bretford CR4500 Series Slim Rectangular Table,957.5775,0.45,-383.0310
23,"Global Deluxe Stacking Chair, Gray",71.3720,0.30,-1.0196
27,"Riverside Palais Royal Lawyers Bookcase, Royal...",3083.4300,0.50,-1665.0522
36,"Electrix Architect's Clamp-On Swing Arm Lamp, ...",190.9200,0.60,-147.9630
38,"Atlantic Metals Mobile 3-Shelf Bookcases, Cust...",532.3992,0.32,-46.9764

## Özet

Bu çalışmada gerçek Superstore satış verisi üzerinde pandas ile veri temizleme ve analiz sürecini uçtan uca uyguladık:

| Adım | Kullanılan Yöntem |
|---|---|
| Genel veri sağlığı kontrolü | `.info()`, `.isnull().sum()`, `.duplicated()` |
| Tarih sütunlarının tipi düzeltme | `pd.to_datetime()` |
| Tarihten yeni sütun türetme | `.dt.year`, `.dt.month`, tarih farkı |
| Aykırı değer tespiti | IQR yöntemi (`quantile`, `IQR`) |
| Aykırı değerleri bayraklama | Boole sütun ekleme |
| Kategori tutarlılığı kontrolü | `.unique()`, `.str.strip()` (Product Name'de 16 satırda boşluk bulundu ve düzeltildi) |
| İndeks düzenleme | `.reset_index(drop=True)` |
| Temiz veriyi kaydetme | `.to_csv()` |
| Uçtan uca fonksiyon | Tüm adımları tek fonksiyonda toplama |